playground/intern/2009/noan/noan/repository/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    # Pending
    (r'^pending/$', 'noan.repository.views.page_pending_index'),
    (r'^pending/(?P<distName>[^/]+)-(?P<distRelease>[^/]+)/$', 'noan.repository.views.page_pending'),

    # Users
    (r'^users/$', 'noan.repository.views.page_users'),
    (r'^users/(?P<userName>[^/]+)/$', 'noan.repository.views.page_user'),

    # Index
    (r'^$', 'noan.repository.views.page_index'),
    # Sources
    (r'^(?P<distName>[^/]+)-(?P<distRelease>[^/]+)/$', 'noan.repository.views.page_sources'),
    # Source
    (r'^(?P<distName>[^/]+)-(?P<distRelease>[^/]+)/(?P<sourceName>[^/]+)/$', 'noan.repository.views.page_source'),
    # Package
    (r'^(?P<distName>[^/]+)-(?P<distRelease>[^/]+)/(?P<sourceName>[^/]+)/(?P<packageName>[^/]+)/$', 'noan.repository.views.page_package'),
    # Binary
    (r'^(?P<distName>[^/]+)-(?P<distRelease>[^/]+)/(?P<sourceName>[^/]+)/(?P<packageName>[^/]+)/(?P<binaryNo>\d+)/$', 'noan.repository.views.page_binary'),
    # search
    (r'^search/$', 'noan.repository.views.search_form'),
    # Maintainer ack/nack list
    (r'^test_list/$','noan.repository.views.user_test_list'),
    # all list of ack/nack
    (r'^test_results/$','noan.repository.views.test_results'),
)

playground/intern/2009/noan/noan/urls.py
from django.conf.urls.defaults import *
from noan.repository.views import log_out
# Enable the admin interface:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Repository
    (r'^$', 'django.views.generic.simple.redirect_to', {'url': '/repository/'}),
    (r'^repository/', include('noan.repository.urls')),

    # Enable the admin interface:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/(.*)', admin.site.root),
    #login
    (r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'registration/login.html'}),
    # logout
    (r'^logout/$',log_out),
)

playground/intern/2009/noan/noan/repository/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from noan.middleware.threadlocals import get_current_lang
import time
from pisi.version import Version as Pisi_Version

TEST_RESULTS = (
    ('yes', _('Can go to stable')),
    ('no', _('Package has problems')),
    ('unknown', _('Tests are incomplete')),
)

RELEASE_RESOLUTIONS = (
    ('pending', _('Pending')),
    ('released', _('Released')),
    ('reverted', _('Reverted')),
    ('removed', _('Removed')),
)


class Distribution(models.Model):
    """
        Database model for distributions.

        name: Name of distribution (Pardus, Pardus x64, ...)
        release: Distribution release (2008, 2009, ...)
    """
    name = models.CharField(max_length=64, verbose_name=_('name'))
    release = models.CharField(max_length=64, verbose_name=_('release'))

    def __unicode__(self):
        return u'%s %s' % (self.name, self.release)

    def get_url(self):
        return '/repository/%s-%s' % (self.name, self.release)

    class Meta:
        verbose_name = _('distribution')
        verbose_name_plural = _('distributions')
        ordering = ['name', 'release']
        unique_together = ('name', 'release')


class Source(models.Model):
    """
        Database model for sources in repository.

        name: Name of the source
        distribution: Distribution that contains the source
        maintained_by: Source maintainer
    """
    name = models.CharField(max_length=64, verbose_name=_('name'))
    distribution = models.ForeignKey(Distribution, verbose_name=_('distribution'))
    maintained_by = models.ForeignKey(User, verbose_name=_('maintained by'))

    def __unicode__(self):
        return u'%s (%s)' % (self.name, self.distribution)

    def get_url(self):
        return '%s/%s' % (self.distribution.get_url(), self.name)

    class Meta:
        verbose_name = _('source')
        verbose_name_plural = _('sources')
        ordering = ['name']
        unique_together = ('name', 'distribution')


class Package(models.Model):
    """
        Database model for package in repository.

        name: Name of the package
        source: Source that contains the package
    """
    name = models.CharField(max_length=64, verbose_name=_('name'))
    source = models.ForeignKey(Source, verbose_name=_('source'))

    def __unicode__(self):
        return _('%(package)s (source: %(source)s, distro: %(distro)s)') % {'package': self.name, 'source': self.source.name, 'distro': self.source.distribution}

    def get_url(self):
        return '%s/%s' % (self.source.get_url(), self.name)

    class Meta:
        verbose_name = _('package')
        verbose_name_plural = _('packages')
        ordering = ['name']
        unique_together = ('name', 'source')


class BuildDependency(models.Model):
    """
        Database model for build dependencies of a source.

        name: Package name of the dependency
        version*: Version range
        release*: Release range
        source: Dependent source
    """
    name = models.CharField(max_length=64, verbose_name=_('name'))
    version = models.CharField(max_length=32, verbose_name=_('version'), default='', blank=True)
    version_from = models.CharField(max_length=32, verbose_name=_('version from'), default='', blank=True)
    version_to = models.CharField(max_length=32, verbose_name=_('version to'), default='', blank=True)
    release = models.IntegerField(verbose_name=_('release'), default=0, blank=True)
    release_from = models.IntegerField(verbose_name=_('release from'), default=0, blank=True)
    release_to = models.IntegerField(verbose_name=_('release to'), default=0, blank=True)
    source = models.ForeignKey(Source, verbose_name=_('dependent source'))

    def __unicode__(self):
        if self.release != 0:
            return u'%s == r%s' % (self.name, self.release)
        if self.version != '':
            return u'%s == %s' % (self.name, self.version)
        dep = []
        if self.version_from != '':
            dep.append('>= %s' % self.version_from)
        if self.version_to != '':
            dep.append('<= %s' % self.version_to)
        if self.release_from != 0:
            dep.append('>= r%s' % self.release_from)
        if self.release_to != 0:
            dep.append('<= r%s' % self.release_to)
        return u'%s %s' % (self.name, ' '.join(dep))

    class Meta:
        verbose_name = _('build dependency')
        verbose_name_plural = _('build depencencies')
        ordering = ['name']


class RuntimeDependency(models.Model):
    """
        Database model for runtime depencencies of a package.

        name: Package name of the depencency
        version*: Version range
        release*: Release range
        package: Dependent package
    """
    name = models.CharField(max_length=64, verbose_name=_('name'))
    version = models.CharField(max_length=32, verbose_name=_('version'), default='', blank=True)
    version_from = models.CharField(max_length=32, verbose_name=_('version from'), default='', blank=True)
    version_to = models.CharField(max_length=32, verbose_name=_('version to'), default='', blank=True)
    release = models.IntegerField(verbose_name=_('release'), default=0, blank=True)
    release_from = models.IntegerField(verbose_name=_('release from'), default=0, blank=True)
    release_to = models.IntegerField(verbose_name=_('release to'), default=0, blank=True)
    package = models.ForeignKey(Package, verbose_name=_('dependent package'))

    def __unicode__(self):
        if self.release != 0:
            return u'%s == r%s' % (self.name, self.release)
        if self.version != '':
            return u'%s == %s' % (self.name, self.version)
        dep = []
        if self.version_from != '':
            dep.append('>= %s' % self.version_from)
        if self.version_to != '':
            dep.append('<= %s' % self.version_to)
        if self.release_from != 0:
            dep.append('>= r%s' % self.release_from)
        if self.release_to != 0:
            dep.append('<= r%s' % self.release_to)
        return u'%s %s' % (self.name, ' '.join(dep))

    class Meta:
        verbose_name = _('runtime dependency')
        verbose_name_plural = _('runtime depencencies')
        ordering = ['name']


class Update(models.Model):
    """
        Database model for updates of a source.

        no: Release number
        source: Source
        version_no: Version string
        updated_by: Updater
        updated_on: Update date
        comment: Updater's comment
    """
    no = models.IntegerField(verbose_name=_('release no'))
    source = models.ForeignKey(Source, verbose_name=_('source'))
    version_no = models.CharField(max_length=32, verbose_name=_('version no'))
    updated_by = models.ForeignKey(User, verbose_name=_('updated by'))
    updated_on = models.DateField(verbose_name=_('updated on'))
    comment = models.TextField(max_length=512, verbose_name=_('comment'))

    def __unicode__(self):
        return _('%(version)s-%(release)s by %(updater)s on %(date)s') % {'version': self.version_no, 'release': self.no, 'updater': self.updated_by, 'date': self.updated_on}

    class Meta:
        verbose_name = _('update')
        verbose_name_plural = _('updates')
        ordering = ['-no']
        unique_together = ('no', 'source')


class Binary(models.Model):
    """
        Database model for binary package.

        no: Build no
        package: Package
        update: Update
        resolution: 'pending', 'released' or 'reverted'. Import scripts set this value.
    """
    created_on = models.DateField(verbose_name=_('created on'), auto_now=True)
    no = models.IntegerField(verbose_name=_('build no'))
    package = models.ForeignKey(Package, verbose_name=_('package'))
    update = models.ForeignKey(Update, verbose_name=_('update'))
    resolution = models.CharField(max_length=32, choices=RELEASE_RESOLUTIONS, verbose_name=_('resolution'))
    linked_binary = models.ManyToManyField('Binary', symmetrical=False)

    def __unicode__(self):
        return u'%s-%s-%s-%s' % (self.package.name, self.update.version_no, self.update.no, self.no)

    def get_url(self):
        return '%s/%s' % (self.package.get_url(), self.no)

    def get_filename(self):
        return '%s.pisi' % unicode(self)

    def get_difference(self):
        """
            Find next to last binary and generates a list of update difference between these two binaries.

            This is an expensive method. Don't use this in pacakge lists.
        """
        binaries = self.package.binary_set.filter(no__lt=self.no).order_by('-no')
        if len(binaries) == 0:
            update_last = 0
        else:
            update_last = binaries[0].update.no
        return self.package.source.update_set.filter(no__lte=self.update.no, no__gt=update_last)

    def get_pending_dependencies(self):
        return self.linked_binary.all()
        """
            Returns a list of dependencies that stay in test repository.

            This is a *very* expensive method. Don't use this in package lists.
        
        dependencies = []
        def _extend(x):
            for y in x:
                if y not in dependencies:
                    dependencies.append(y)
        for dep in self.package.runtimedependency_set.all():
            binaries = Binary.objects.filter(package__source__distribution = self.package.source.distribution, package__name=dep.name)
            # version
            if dep.version != "" and binaries.filter(update__version_no=dep.version, resolution="released").count() == 0:
                _extend(binaries.filter(resolution="pending"))
            elif dep.version_from != "":
                in_stable = False
                for bin in binaries.filter(resolution="released"):
                    if Pisi_Version(bin.update.version_no) >= Pisi_Version(dep.version_from):
                        in_stable = True

playground/intern/2009/noan/templates/repository/ack_nack.html
{% extends 'base.html' %}
{% block content %}
{% if error %}
Get some Error :<br/> {{error}}
{% endif %}
<h1>Ack/Nack</h1>
{% if stateBinarys  or stateBinarysOfUpdate %}
<div style="float:left;padding-left:10px">
    <form action="." method="post">
        <table class="altrowstable">
            {% for distro in distributions %}

            <tr>
                <th colspan="6">
                    <u><strong>{{distro}}</strong></u>
                </th>
            </tr>
            <tr><th>Maintained<br/>or Updated</th><th>Package Name</th><th>Ack</th><th>Nack</th><th>Null</th><th>Comment</th></tr>
        {% if stateBinarys %}
        {% for stateBinary in stateBinarys.object_list %}
            {% ifequal stateBinary.package.source.distribution distro %}
            <tr onmouseover="this.style.backgroundColor='#d4e3e5';" onmouseout="this.style.backgroundColor='#ffffff';" >
                <td>
                    {% ifequal stateBinary.package.source.maintained_by user%}
                    Maintained
                    {% else %}
                    Updated
                    {% endifequal %}
                </td>
                <td>
                    <div class="test_{{stateBinary.is_Ack}}" >
                        {{stateBinary}}
                    </div>
                </td>
                <td>
                    <input type="radio" name="{{stateBinary.id}}-radio" value="yes"/>
                </td>
                <td>
                    <input type="radio" name="{{stateBinary.id}}-radio" value="no"/>
                </td>
                <td>
                    <input type="radio" name="{{stateBinary.id}}-radio" value=""/>
                 </td>
                 <td><input type="text" name="{{stateBinary.id}}-comment" /></td>
            </tr>
            {% endifequal %}
        {% endfor %}
        {% endif %}
{% endfor %}
<tr><td colspan="5"><input type="submit"/></tr>
        </table>
    </form>
   <div class="pagination">
        <span class="step-links">
            {% if stateBinarys.has_previous %}
                <a href="?page={{ stateBinarys.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ stateBinarys.number }} of {{ stateBinarys.paginator.num_pages }}.
            </span>

            {% if stateBinarys.has_next %}
                <a href="?page={{ stateBinarys.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div> 
{% endif %}
</div>
{% endblock %}

playground/intern/2009/noan/templates/repository/acks_nacks.html
{% extends 'base.html' %}
{% block content %}
<h1>Ack/Nack</h1>
<div style="float:left;padding-left:10px">
    <table class="altrowstable">
        {% for distro in distributions %}
            <tr>
                <th colspan="5">
                    <u><strong>{{distro}}</strong></u>
                </th>
            </tr>
            <tr><th>Package Name</th><th>State</th><th>Comment</th></tr>
            {% for list in AckNackList %}
                {% ifequal list.binary.package.source.distribution distro %}
                    <tr onmouseover="this.style.backgroundColor='#d4e3e5';" onmouseout="this.style.backgroundColor='#ffffff';" >
                        <td>
                            {% ifequal list.result "no" %}
                                <div style="color:#ba0000" >
                                    {{ list.binary }}
                                </div>
                            {% else %}
                            <div style="color:#007f00">
                                {{ list.binary }}
                                </div>
                            {% endifequal %}
                        </td>
                        <td>
                            {{list.result}}
                        </td>
                        <td>
                            {{list.comment}}
                        </td>
                    </tr>
                {% endifequal %}
            {% endfor %}
        {% endfor %}
        <tr>
    </table>
</div>
{% endblock %}

playground/intern/2009/noan/templates/repository/binary.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{ binary }}</h1>
    <ul>
        <li><strong>Distribution:</strong> <a href="{{ binary.package.source.distribution.get_url }}">{{ binary.package.source.distribution }}</a></li>
        <li><strong>Source:</strong> <a href="{{ binary.package.source.get_url }}">{{ binary.package.source.name }}</a></li>
        <li><strong>Package:</strong> <a href="{{ binary.package.get_url }}">{{ binary.package.name }}</a></li>
        <li><strong>Updated By:</strong> <a href="/repository/users/{{ binary.update.updated_by.username }}/">{{ binary.update.updated_by.get_full_name }}</a></li>
        <li><strong>Status:</strong> {{ binary.resolution }}</li>
    </ul>

    {% ifequal binary.resolution "pending" %}
    <h2>Pending Dependencies</h2>
    <ul>
        {% for dep in binary.get_pending_dependencies %}
        <li><a href="{{ dep.get_url }}">{{ dep }}</a> [Test Result: {{ dep.get_result_str }}]</li>
        {% endfor %}
    </ul>

    <h2>Test Result</h2>
    <p>
        Current result: {{ binary.get_result_str }}
        </p>
    {% if binary.testresult_set.all  %}
    <h2>Results</h2>
    <table>
        <tr><th>User</th><th>Result</th><th>Time</th></tr>
        {% for results in binary.testresult_set.all %}

        <form action="." method="post"  >
            <input type="hidden" name="tested_by" value="{{results.created_by}}">
            <tr><td>{{results.created_by}}</td><td>{{results.result}}</td><td>{{results.created_on}}</td>
                {% if perms.repository.can_submit %}
                <td><button {% ifequal results.result "yes" %}style="background-color: #0b0;"{% endifequal %} type="submit" name="RepoAdminResult" value="yes" >Yes</button></td>
                <td><button {% ifequal results.result "no" %}style="background-color: #b00;"{% endifequal %} type="submit" name="RepoAdminResult" value="no" >No</button></td>
                <td><button {% ifequal results.result "unknown" %}style="background-color: #bbb;"{% endifequal %} type="submit" name="RepoAdminResult" value="unknown" >Delete</button></td>
                {% endif %}
            </tr>
        </form>
        {% endfor %}
    </table>
    {% endif %}
    <h2>Your Report</h2>
        {{ test }}
        {% if user.is_authenticated %}
        <form action="" method="post">
            <button {% ifequal user_result "yes" %}style="background-color: #0b0;"{% endifequal %} type="submit" name="result" value="yes" >Yes</button>
            <button {% ifequal user_result "no" %}style="background-color: #b00;"{% endifequal %} type="submit" name="result" value="no" >No</button>
            <button {% ifequal user_result "unknown" %}style="background-color: #bbb;"{% endifequal %} type="submit" name="result" value="unknown" >Not Tested</button>
        </form>
        {% endif %}
    {% endifequal %}

    <h2>Difference</h2>
    <ul>
        {% for update in binary.get_difference %}
        <li>
            <p>{{ update }}</p>
            <p>{{ update.comment|linebreaks }}</p>
        </li>
        {% endfor %}
    </ul>
{% endblock %}

playground/intern/2009/noan/templates/repository/index.html
{% extends 'base.html' %}
{% block content %}
    <h1>Distributions</h1>
    <ul>
        {% for dist in distributions %}
        <a href="{{ dist.get_url }}">{{ dist }}</a>
        <ul>
            <li>Sources: {{ dist.source_set.count }}</li>
            <li>updates:</li><table>
        <tr>
            <th>Package name</th>
            <th>Version no</th>
            <th>Update time</th>
            <th>M. name</th>
            <th>M. last name</th>
        </tr>
        {%for repo , packages in updates%}
            {%ifequal repo dist %}
                {%for package in packages%}
                    <tr>
                    <td>{{ package.source.name }}</td>
                    <td>{{package.version_no}}</td>
                    <td>{{package.updated_on }}</td>
                    <td><a href="/repository/users/{{package.source.maintained_by.username}}">{{package.source.maintained_by.first_name}}</td></a>
                    <td>{{package.source.maintained_by.last_name}}</td>
                    </tr>
                {%endfor%}
            {%endifequal%}
        {% endfor %}
            </table>
        </ul>
        {% endfor %}
    </ul>
{% endblock %}

playground/intern/2009/noan/templates/repository/package.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{ package.name }}</h1>
    <ul>
        <li><strong>Distribution:</strong> <a href="{{ package.source.distribution.get_url }}">{{ package.source.distribution }}</a></li>
        <li><strong>Source:</strong> <a href="{{ package.source.get_url }}">{{ package.source.name }}</a></li>
        <li><strong>Maintained By:</strong> <a href="/repository/users/{{ package.source.maintained_by.username }}/">{{ package.source.maintained_by.get_full_name }}</a></li>
    </ul>

    <h2>Checklist</h2>
    <ul>
        {% for task in package.task_set.all %}
        <li>{{ task.get_description }}</li>
        {% endfor %}
    </ul>

    <h2>Runtime Dependencies</h2>
    <ul>
        {% for dep in package.runtimedependency_set.all %}
        <li>{{ dep }}</li>
        {% endfor %}
    </ul>

    <h2>Binaries</h2>
    <ul>
        {% for binary in package.binary_set.all %}
        <li><a href="{{ binary.get_url }}">{{ binary.get_filename }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

playground/intern/2009/noan/templates/repository/pending-index.html
{% extends 'base.html' %}
{% block content %}
    <h1>Distributions</h1>
    <ul>
        {% for dist in distributions %}
        <li>
            <a href="/repository/pending/{{ dist.name }}-{{ dist.release }}">{{ dist }}</a>
        </li>
        {% endfor %}
    </ul>
{% endblock %}

playground/intern/2009/noan/templates/repository/pending.html
{% extends 'base.html' %}
{% block content %}
    <table class="package_list">
        <tr>
            <th>Package</th>
            <th>Updated By</th>
            <th>Distribution</th>
            <th>Time</th>
        </tr>
        {% for binary in binaries.object_list %}
        <tr class="test_{{ binary.get_result }}">
            <td><a href="{{ binary.get_url }}">{{ binary }}</a></td>
            <td>{{ binary.update.updated_by.get_full_name }}</td>
            <td>{{ binary.package.source.distribution }}</td>
            <td>{{binary.created_on}}</td>
        </tr>
        {% endfor %}
    </table>

    <p></p>

    <div class="pagination">
        <span class="step-links">
            {% if binaries.has_previous %}
                <a href="?page={{ binaries.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ binaries.number }} of {{ binaries.paginator.num_pages }}.
            </span>

            {% if binaries.has_next %}
                <a href="?page={{ binaries.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

playground/intern/2009/noan/templates/repository/search.html
{% extends 'base.html'%}
{% block content %}
{%ifequal  results [] %}
<h1>Searching</h1>
<form action="" method="post">
    <table>
        <tr>
            <td>Keyword</td>
            <td>:<input type="text" name="question"/></td>
        </tr>
        <tr>
            <td>Search on</td>
            <td>:<input type="radio" name="search_area" value="package" checked="checked"/>Package Name
                <input type="radio" name="search_area" value="source"/>Source name
            </td>
        </tr>
        <tr>
            <td>
                Distributions
            </td>
            <td>
                :<select name="distro">
                    <option value="null" selected="selected">any</option>
                    {% for distro in distributions  %}
                    <option value="{{distro.id}}">{{distro}}</option>
                    {% endfor %}
                </select>
            </td>
        </tr>
        <tr>
            <td><input type="submit" value="Search"/></td>
            <td><input type="reset" value="Reset"/></td>
        </tr>
    </table>
</form>
{%else%}<table>
    <ul>{%for distro in distributions  %}{{post}}
    <tr><td></td><td><h2> {{distro}} </h2><td></td><td></td></tr>
        <tr><td><b>Name </b></td><td><b>Resolution </b></td><td><b>Update time</b></td><td><b>Maintainer </b></td></tr>
    {%for result in results %}
    {%ifequal result.source.distribution distro%}
{%for binary in result.binary_set.all%}
<tr>
    <td><a href="{{ binary.get_url }}">{{ binary }}</a></td>
    <td>{{ binary.resolution }}</td>
    <td>{{ binary.update.updated_on }}</td>
    <td><a href="/repository/users/{{ result.source.maintained_by }}">{{ result.source.maintained_by }}</a></td>
</tr>{%endfor%}
{%endifequal%}
{%endfor%}
{%endfor%}</table>
</ul>
{% endifequal %}
{%endblock%}

playground/intern/2009/noan/templates/repository/source.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{ source.name }}</h1>
    <ul>
        <li><strong>Distribution:</strong> <a href="{{ source.distribution.get_url }}">{{ source.distribution }}</a></li>
        <li><strong>Maintained By:</strong> <a href="/repository/users/{{ source.maintained_by.username }}/">{{ source.maintained_by.get_full_name }}</a></li>
    </ul>

    <h2>Packages</h2>
    <ul>
        {% for package in source.package_set.all %}
        <li><a href="{{ package.get_url }}">{{ package.name }}</a></li>
        {% endfor %}
    </ul>

    <h2>Build Dependencies</h2>
    <ul>
        {% for dep in source.builddependency_set.all %}
        <li>{{ dep }}</li>
        {% endfor %}
    </ul>

    <h2>Updates</h2>
    <ul>
        {% for update in source.update_set.all %}
        <li>
            <p>{{ update }}</p>
            <p>{{ update.comment|linebreaks }}</p>
        </li>
        {% endfor %}
    </ul>
{% endblock %}

playground/intern/2009/noan/templates/repository/sources.html
{% extends 'base.html' %}
{% block content %}
    <table class="package_list">
        <tr>
            <th>Package</th>
            <th>Maintainer</th>
            <th>Distribution</th>
        </tr>
        {% for source in sources.object_list %}
        <tr>
            <td><a href="{{ source.get_url }}">{{ source.name }}</a></td>
            <td>{{ source.maintained_by.get_full_name }}</td>
            <td>{{ source.distribution }}</td>
        </tr>
        {% endfor %}
    </table>

    <p></p>

    <div class="pagination">
        <span class="step-links">
            {% if sources.has_previous %}
                <a href="?page={{ sources.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ sources.number }} of {{ sources.paginator.num_pages }}.
            </span>

            {% if sources.has_next %}
                <a href="?page={{ sources.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

playground/intern/2009/noan/templates/repository/user.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{ developer.get_full_name }}</h1>

    <h2>Pending Binaries</h2>
    <ul>
        {% for distro in distros %}
        <li>
            {{ distro }}
            <ul>
                {% for binary in pending %}
                <li><a href="{{ binary.get_url }}">{{ binary.get_filename }}</a></li>
                {% endfor %}
            </ul>
        </li>
        {% endfor %}
    </ul>

    <h2>Sources</h2>
    <ul>
        {% for distro in distros %}
        <li>
            {{ distro }}
            <ul>
                {% for source in developer.source_set.all %}
                    {% ifequal source.distribution distro %}
                    <li><a href="{{ source.get_url }}">{{ source.name }}</a></li>
                    {% endifequal %}
                {% endfor %}
            </ul>
        </li>
        {% endfor %}
    </ul>

    <h2>Updates</h2>
    <ul>
        {% for distro in distros %}
        <li>
            {{ distro }}
            <ul>
                {% for update in developer.update_set.all %}
                    {% ifequal update.source.distribution distro %}
                    <li>{{ update.source.name }} - release {{ update.no }}</li>
                    {% endifequal %}
                {% endfor %}
            </ul>
        </li>
        {% endfor %}
    </ul>
{% endblock %}

playground/intern/2009/noan/templates/repository/users.html
{% extends 'base.html' %}
{% block content %}
    <table class="package_list">
        <tr>
            <th>Developer</th>
        </tr>
        {% for dev in developers.object_list %}
        <tr>
            <td><a href="/repository/users/{{ dev.username }}">{{ dev.get_full_name }}</a></td>
        </tr>
        {% endfor %}
    </table>

    <p></p>

    <div class="pagination">
        <span class="step-links">
            {% if developers.has_previous %}
                <a href="?page={{ developers.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ developers.number }} of {{ developers.paginator.num_pages }}.
            </span>

            {% if developers.has_next %}
                <a href="?page={{ developers.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
{% endblock %}