playground/renan/projects/staj/urls.py
from django.conf.urls.defaults import *
from staj.form.views import *
from django.conf import settings

path = "/home/pars/workspace/staj"

urlpatterns = patterns('',
        #(r'^staj/$', intern_form),
        (r'^staj/$', end),
        (r'^$', end),

        (r'^internshop/$', scoring_form),

        #(r'^kayit/$', thanks),

        #(r'^mentor/$', mentor_form),
        #(r'^mentor/done$', mentor_done),
        (r'^[A-Za-z/]*dosyalar/cv/(?P<path>.*)$', 'django.views.static.serve',{'document_root': '%s/uploads/cv' % path, 'show_indexes': False}),
        (r'^[A-Za-z/]*dosyalar/kod/(?P<path>.*)$', 'django.views.static.serve',{'document_root': '%s/uploads/code/' % path, 'show_indexes': False}),

        (r'^[A-Za-z/]*js/(?P<path>.*)$', 'django.views.static.serve',{'document_root': '%s/templates/media_files/js/' % path, 'show_indexes': False}),
        (r'^[A-Za-z/]*img/(?P<path>.*)$', 'django.views.static.serve',{'document_root': '%s/templates/media_files/img/' % path, 'show_indexes': False}),
        (r'^[A-Za-z/]*css/(?P<path>.*)$', 'django.views.static.serve',{'document_root': '%s/templates/media_files/css/' % path, 'show_indexes': False}),
        #(r'^projeler/$', projeler),
        url(r'^captcha/', include('captcha.urls')),
)

playground/renan/projects/staj/form/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from django.db import models
from django.forms import ModelForm

class ProgrammingLanguagesAndFrameworks(models.Model):
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return u'%s' % (self.name)



class Mentor(models.Model):
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    email = models.EmailField()
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=30)

    def __unicode__(self):
       return u'%s %s' % (self.name, self.surname)


class Project(models.Model):
    name = models.TextField()
    objective = models.TextField()
    todo = models.TextField()
    prerequisites = models.TextField()
    references = models.TextField()
    score = models.TextField()
    mentors = models.ManyToManyField(Mentor)

    def __unicode__(self):
       return u'%s' % (self.name)

    class Meta:
        ordering = ('name',)



class Vote(models.Model):
    vote = models.TextField(max_length=10)
    mentor = models.ForeignKey(Mentor)


class Comment(models.Model):
    comment = models.TextField(max_length=2000)
    timestamp = models.DateTimeField(auto_now = True)
    mentor = models.ForeignKey(Mentor)

    def __unicode__(self):
       return u'%s' % (self.comment)

class Student(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    birthdate = models.DateField(max_length=50)
    gender = models.CharField(max_length=1)
    id_number = models.CharField(max_length=11)
    mobile_phone = models.CharField(max_length=11)
    address = models.CharField(max_length=100)
    district = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    jabber = models.EmailField(max_length=100, null=True)
    website = models.URLField(max_length=100, null=True)
    school = models.CharField(max_length=100)
    department = models.CharField(max_length=100)
    grade = models.CharField(max_length=100)
    semester = models.CharField(max_length=100)
    expected_grad_date = models.EmailField(max_length=100)
    gpa = models.CharField(max_length=10)
    mandatory_internship = models.CharField(max_length=1)
    english = models.CharField(max_length=100)
    programming_languages_and_frameworks = models.ManyToManyField(ProgrammingLanguagesAndFrameworks, max_length=50)

    other_programming_languages = models.CharField(max_length=100, null=True)
    awards = models.CharField(max_length=1000, null=True)
    why_pardus = models.CharField(max_length=1000)
    projects_done = models.CharField(max_length=1000, null=True)
    where_did_you_hear = models.CharField(max_length=1000)
    linux_experience = models.CharField(max_length=1000)
    prefered_os = models.CharField(max_length=1000)

    more = models.CharField(max_length=1000, null=True)
    suitable_date = models.CharField(max_length=50)

    #prefered_projects = models.ManyToManyField(Project, max_length=200)
    commited_before = models.CharField(max_length=100)

    cv_upload = models.FileField(upload_to='attachments')
    code_upload = models.FileField(upload_to='attachments', null=True)

    comment = models.ManyToManyField(Comment, max_length=2000)

    vote = models.ManyToManyField(Vote, max_length=10)
    total_yes_votes = models.IntegerField(null=True)
    total_no_votes = models.IntegerField(null=True)


    def __unicode__(self):
        return u'%s %s' % (self.name, self.surname)

"""
class CommentsAndVotes(models.Model):
    vote = models.TextField(max_length=10)
    comment = models.TextField(max_length=2000)
    student = models.ManyToManyField(Student)
    mentor = models.ManyToManyField(Mentor)

    def __unicode__(self):
        return u'%s %s' % (self.comment, self.vote)
"""

"""
class ScoringModel(models.Model):
"""

"""
Hold score information of the given fields
    student = models.OneToOneField(Student)
    mentor = models.OneToOneField(Mentor)
    score = models.CharField(max_length=5)
    comment = models.CharField(max_length=2000)
"""

playground/renan/projects/staj/form/views.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

import datetime
from django.shortcuts import render_to_response
import MySQLdb
from django.http import HttpResponseRedirect

from django import forms

from staj.form.models import *

from staj.captcha.fields import CaptchaField

from django.forms.util import ErrorList

from django.db.models import F

import os

from django.core.paginator import Paginator

GENDER_CHOICES = (  (u'M', u'Erkek'),
                    (u'F', u'Kadın'))

DATE_CHOICES = (  (u'20 Haziran - 15 Temmuz 2011', u'20 Haziran - 15 Temmuz 2011'),
                  (u'1 Ağustos - 26 Eylül 2011', u'1 Ağustos - 26 Eylül 2011'),
                  (u'Farketmez', u'Farketmez')
                  )

SCORE_CHOICES =  (  (u'1', u'1'),
                    (u'2', u'2'),
                    (u'3', u'3'),
                    (u'4', u'4'),
                    (u'5', u'5'),
                    (u'6', u'6'),
                    (u'7', u'7'),
                    (u'8', u'8'),
                    (u'9', u'9'),
                    (u'10', u'10'),
                    )

GRADE_CHOICES =  (  (u'1', u'1'),
                    (u'2', u'2'),
                    (u'3', u'3'),
                    (u'4', u'4'),
                    )

ENGLISH_CHOICES = ( (u'Başlangıç',u'Başlangıç'),
                    (u'Orta', u'Orta'),
                    (u'İyi', u'İyi'),
                    (u'Çok İyi', u'Çok İyi'),
                    )


YES_NO = (  (u'E', u'Evet'),
            (u'H', u'Hayır'))


"""
class ScoringForm(forms.Form):
    name = forms.CharField()
    surname = forms.CharField()
    birthdate = forms.CharField()
    gender = forms.CharField()
    id_number = forms.CharField()
    address = forms.CharField()
    district = forms.CharField()
    city = forms.CharField()
    email = forms.CharField()
    website = forms.CharField()
    school = forms.CharField()
    department = forms.CharField()
    gpa = forms.CharField()
    programming_languages_and_frameworks = forms.CharField()
    other_programming_languages = forms.CharField()
    awards = forms.CharField()
    why_pardus = forms.CharField()
    projects_done = forms.CharField()
    where_did_you_hear = forms.CharField()
    suitable_date = forms.CharField()
    prefered_projects = forms.CharField()
    commited_before = forms.CharField()
    cv_upload = forms.CharField()
    code_upload = forms.CharField()
"""

class InternForm(forms.Form):
    name = forms.CharField(max_length=50, label="Ad", widget=forms.TextInput(attrs={'class':'validate[required]'}))
    surname = forms.CharField(max_length=50, label="Soyad", widget=forms.TextInput(attrs={'class':'validate[required]'}))
    birthdate = forms.DateField(('%d.%m.%Y',), label="Doğum Tarihi (örnek: 24.03.1988)", widget = forms.DateTimeInput(format='%d.%m.%Y', attrs={'class':'validate[required]','size':'15'}))
    gender = forms.ChoiceField(GENDER_CHOICES,label="Cinsiyet",widget=forms.Select(attrs={'class':'validate[required] short'}))
    id_number = forms.CharField(label="T.C. Kimlik No", max_length=11, widget=forms.TextInput(attrs={'class':'validate[required,custom[number]]'}))
    mobile_phone = forms.CharField(label="Cep Telefonu (örnek: 05001234567)", max_length=11, widget=forms.TextInput(attrs={'class':'validate[required,custom[phone],minSize[11]]'}))
    address = forms.CharField(label="Ev Adresi", max_length=100, widget=forms.TextInput(attrs={'class':'validate[required]'}))
    district = forms.CharField(label="Semt", max_length=50, widget=forms.TextInput(attrs={'class':'validate[required]'}))
    city = forms.CharField(label="Şehir", max_length=50, widget=forms.TextInput(attrs={'class':'validate[required]'})) # SEHIR LISTESI
    email = forms.EmailField(label="E-posta Adresi", max_length=100, widget=forms.TextInput(attrs={'class':'validate[required,custom[email]]'}))
    email_verify = forms.EmailField(label="E-posta Adresi (Tekrar)", max_length=100, widget=forms.TextInput(attrs={'class':'validate[required,custom[email]]'}))
    jabber = forms.EmailField(label="Jabber Hesabı", max_length=100, widget=forms.TextInput(attrs={}), required=False)
    website = forms.URLField(label="Web Sitesi", max_length=100, required=False, widget=forms.TextInput())
    school = forms.CharField(label="Üniversite Adı", max_length=100, widget=forms.TextInput(attrs={'class':'validate[required]'}))
    department = forms.CharField(label="Bölüm", max_length=100, widget=forms.TextInput(attrs={'class':'validate[required]'}))
    grade = forms.ChoiceField(GRADE_CHOICES, label="Kaçıncı Sınıftasınız?", widget=forms.Select(attrs={'class':'validate[required] short'}))
    semester = forms.ChoiceField(SCORE_CHOICES, label="Hazırlık Hariç Toplam Kaç Dönemdir Üniversitedesiniz?", widget=forms.Select(attrs={'class':'validate[required] short'}))
    expected_grad_date = forms.DateField(('%d.%m.%Y',), label="Tahmini Mezuniyet Tarihi (örnek: 17.06.2013)", widget = forms.DateTimeInput(format='%d.%m.%Y', attrs={'class':'validate[required]','size':'15'}))
    gpa = forms.CharField(label="Not Ortalaması (örnek: 2.65)", max_length=10, widget=forms.TextInput(attrs={'class':'validate[required,custom[number]]'}))
    mandatory_internship = forms.ChoiceField(YES_NO,label="Stajınız Zorunlu mu?",widget=forms.Select(attrs={'class':'validate[required] short'}))
    english = forms.ChoiceField(ENGLISH_CHOICES,label="İngilizce Seviyesi",widget=forms.Select(attrs={'class':'validate[required] short'}))
    programming_languages_and_frameworks = forms.ModelMultipleChoiceField(
            queryset = ProgrammingLanguagesAndFrameworks.objects.all(), 
            label="Hakim olduğunuz programlama dilleri ve Frameworkler",
            widget = forms.CheckboxSelectMultiple(attrs={'class':'validate[minCheckbox[2]]'})
            )
    other_programming_languages = forms.CharField(label = "Hakim olduğunuz diğer programlama dilleri", max_length = 100, required=False)
    awards = forms.CharField(label = "Başarı ve Ödüller (En çok 1000 karakter)", widget = forms.Textarea, max_length=1000, required=False)
    why_pardus = forms.CharField(label = "Neden Pardus'ta staj yapmak istediğinizi, Pardus'un size nasıl bir katkı sağlayacağını kısaca yazınız (En çok 1000 karakter)", max_length=1000, widget = forms.Textarea(attrs={'class':'validate[required,maxSize[1000]]'}))
    projects_done = forms.CharField(label = "Projeleriniz (En çok 1000 karakter)", widget=forms.Textarea(attrs={'class':'validate[maxSize[1000]]'}), max_length=1000, required=False)
    where_did_you_hear = forms.CharField(label = "Stajı nereden duydunuz? (En çok 1000 karakter)", max_length=1000, widget = forms.Textarea(attrs={'class':'validate[required,maxSize[1000]]'}))
    linux_experience = forms.CharField(label = "Linux deneyimleriniz (En çok 1000 karakter)", max_length=1000, widget = forms.Textarea(attrs={'class':'validate[required,maxSize[1000]]'}))
    prefered_os = forms.CharField(label = "Bilgisayarınızda aktif olarak bir Linux dağıtımı kullanıyor musunuz? Evet ise hangisi/hangileri?", max_length=100, widget = forms.TextInput(attrs={'class':'validate[required,maxSize[100]]'}))

    more = forms.CharField(label = "Açıklamalar (En çok 1000 karakter)", max_length=1000, widget = forms.Textarea(attrs={'class':'validate[maxSize[1000]]'}), required=False)
    suitable_date = forms.ChoiceField(DATE_CHOICES, label = "Hangi tarih aralıklarında staj yapabileceğinizi belirtiniz")

    #prefered_projects = forms.ModelMultipleChoiceField(queryset = Project.objects.all(),
    #        label = "Staj sırasında üzerinde çalışmak istediğiniz projeler (Birden fazla seçim yapabilirsiniz)",
    #        widget = forms.SelectMultiple(attrs={'class':'validate[required]'})
    #        )

    commited_before = forms.CharField(label="Daha önce Pardus'a katkıda bulundunuz mu? Açıklayınız. (En çok 200 karakter)", max_length = 200, widget = forms.Textarea(attrs={'class':'validate[required,maxSize[200]]'}))
    cv_upload = forms.FileField(label="Özgeçmiş Yükleme. Yüklediğiniz dosya pdf veya odt formatında ve 1 MB'den küçük olmalıdır.", widget = forms.FileInput(attrs={'class':'validate[required]'}))
    code_upload = forms.FileField(label="Kod Yükleme. Yüklediğiniz dosya tar.gz formatında ve 10 MB'den küçük olmalıdır. )", required=False)
    captcha = CaptchaField(label="Doğrulama Metni")

    def clean(self):
        content_types = ('application/pdf', 'application/vnd.oasis.opendocument.text')
        file_exts = ('.odt', '.pdf')

        cleaned_data = self.cleaned_data

        id_number = cleaned_data.get("id_number")
        cv = cleaned_data.get("cv_upload")
        code = cleaned_data.get("code_upload")

        if id_number:
            if not (id_number.isdigit() and len(id_number)==11):
                self._errors["id_number"] = ErrorList(["Lütfen geçerli bir T.C kimlik numarası giriniz."])
            else:
                total = 0
                for i in range(0,10):
                    total += int(id_number[i])

                total = str(total)

                if not total.endswith(id_number[10]):
                    self._errors["id_number"] = ErrorList(["Lütfen geçerli bir T.C kimlik numarası giriniz. no check"])

            if not len(id_number) == 11:
                self._errors["id_number"] = ErrorList(["Lütfen geçerli bir T.C kimlik numarası giriniz."])

        if cv:
            if not cv.content_type in content_types:
                self._errors["cv_upload"] = ErrorList(["Yüklediğiniz dosya odt ya da pdf formatında olmalıdır."])

            if not cv.name.endswith(file_exts):
                self._errors["cv_upload"] = ErrorList(["Yüklediğiniz dosya odt ya da pdf formatında olmalıdır."])

            if cv.size > 1024 * 1024:
                self._errors["cv_upload"] = ErrorList(["Yüklediğiniz dosyanın boyutu 1 Mb'den küçük olmalıdır."])


        if code:
            if code.size > 1024 * 1024 * 10:

playground/renan/projects/staj/templates/form.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>
    <head>
        <title>Başvuru Formu</title>

    <style>

*{ margin:0; padding:0;}
body{ font:100% normal sans-serif, Arial, Helvetica;}
form,input,select,textarea{margin:0; padding:0; color:#333333; font-size: 12pt;}

div.box {
padding: 0px;
margin:0 auto;
width:340px;
/*background:#222222;*/
position:relative;
top:50px;
border:0px solid #262626;
}

div.box h1 {
font-family: sans-serif, Arial, Helvetica;
text-shadow: 1px 1px 1px #ffffff;
margin: 0px;
color:#334455;
font-size:24pt;
padding:5px 0 5px 0px;
letter-spacing: -3px;
}

div.box h1.errors {
font-family: sans-serif, Arial, Helvetica;
text-shadow: 1px 1px 1px #ffffff;
margin: 0px;
color:#990000;
font-size:24pt;
padding:5px 0 5px 0px;
letter-spacing: -3px;
}


div.box h2 {
font-family: sans-serif, Arial, Helvetica;
text-shadow: 1px 1px 1px #ffffff;
margin: 0px;
line-height: 0px;
color:#334455;
font-size:15pt;
padding:5px 0 5px 0px;
font-weight: normal;
}

input[type="checkbox"] {
text-shadow: 1px 1px 1px #ffffff;
background: transparent;
padding:5px 0 5px 0;
margin:2px;
}

div.element ul:first-child li {
    float: left;
    width: 150px;
    margin: 3px;
    list-style-type: none;
}

input[type="text"] {
padding:10px 10px;
width:100%;
background:#f0f0f0;
border-bottom: 1px double #d7d7d7;
border-top: 1px double #d7d7d7;
border-left:1px double #d3d3d3;
border-right:1px double #d3d3d3;
}

select {

margin:0px;
width: 100%;
padding:10px 10px;
}

.short {
width: 150px;
}

textarea{
padding:7px 7px;
width:100%;
overflow:hidden;
height:150px;
background:#f0f0f0;
border-bottom: 1px double #d7d7d7;
border-top: 1px double #d7d7d7;
border-left:1px double #d3d3d3;
border-right:1px double #d3d3d3;

}

div.box .button
{
margin:0 0 10px 0;
padding:4px 7px;
background:#CC0000;
border:0px;
position: relative;
top:10px;
left:382px;
width:100px;
border-bottom: 1px double #660000;
border-top: 1px double #660000;
border-left:1px double #FF0033;
border-right:1px double #FF0033;
}

div.header
{
}

.errorlist li {
    color: #ff5555;
    margin: 0px;
    padding: 0px;
    float: none;
    width: 100%;
}

div.field {
margin-bottom: 20px;
display: table;
width: 100%;

/*
background: #f0f0f0;
-webkit-border-radius: 3px;
-moz-border-radius: 3px;
border-radius: 3px;
*/
}

div.element {
}

div.label {
color: #334455;
text-shadow: 1px 1px 1px #ffffff;
/*
-webkit-border-top-left-radius: 3px;
-webkit-border-top-right-radius: 3px;
-moz-border-radius-topleft: 3px;
-moz-border-radius-topright: 3px;
border-top-left-radius: 3px;
border-top-right-radius: 3px;
*/
margin:0px;
padding: 0px;
}


    </style>


    <link type="text/css" href="css/smoothness/jquery-ui-1.8.10.custom.css" rel="Stylesheet" />
    <script type="text/javascript" src="js/jquery-1.4.4.min.js"></script>
    <script type="text/javascript" src="js/jquery-ui-1.8.10.custom.min.js"></script>
    <script type="text/javascript" src="js/jquery.ui.datepicker-tr.js"></script>

    <script src="js/jquery.validationEngine-en.js" type="text/javascript" charset="utf-8"></script>
    <script src="js/jquery.validationEngine.js" type="text/javascript" charset="utf-8"></script>
    <link rel="stylesheet" href="css/validationEngine.jquery.css" type="text/css"/>

    <script type="text/javascript" src="js/jquery.asmselect.js"></script>
    <link rel="stylesheet" type="text/css" href="css/jquery.asmselect.css" />


    <script>

        jQuery(document).ready(function(){
            jQuery("#form").validationEngine();
        });


        $(function(){
            $('#id_birthdate').datepicker(
                {
                    changeYear: true, yearRange: 'c-30'
                }
            );

            $('#id_expected_grad_date').datepicker(
                {
                    changeYear: true
                }
            );


        $("select[multiple]").asmSelect({
                addItemTarget: 'bottom',
                animate: true,
                highlight: true,
                sortable: false
            });

        });


    </script>

    </head>
    <body>
        {% include "header.html" %}

        <div class="box">
        <h1>Başvuru Formu</h1>
        <p>Formu doldurmaya başlamadan önce lütfen <a target="_blank" href="http://tr.pardus-wiki.org/Staj2011">Staj 2011 belgesini</a> okuyunuz.</p>
        {% if form.errors %}
            <h1 id='errors' class="errors">
                Form Hatalar İçeriyor!
            </h1>
            Lütfen aşağıda bulunan hataları düzeltip tekrar deneyiniz.

<br><br>
            <div class="errorlist">
            <ul>

            {% for e in form %}
                {% if e.errors %}
                    <li>{{e.label}}</li>
                {% endif %}
            {% endfor %}
            </ul>
            </div>
        {% endif %}

<br><br>

        <form id="form" enctype="multipart/form-data" action="/staj/" method="post">
            {% for element in form %}
            <div class="field">
                <div class="label">{{ element.label }}</div>
                <div class="error">{{ element.errors }}</div>
                <div class="element">{{ element }}</div>
            </div>

            {% endfor %}

        <input type="submit" value="Gönder">
        </form>
        </div>

    </body>
</html>

playground/renan/projects/staj/templates/index.html
<iframe src ="http://www.igi-global.com" width="100%" height="800">
      <p>Your browser does not support iframes.</p>
  </iframe>

playground/renan/projects/staj/templates/kayit.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>
    <head>
        <title>Pardus Staj Başvuru Formu</title>

        <style type="text/css">

*{ margin:0; padding:0;}
body{ font:100% normal sans-serif, Arial, Helvetica;background:url("") repeat-x fixed;}
form,input,select,textarea{margin:0; padding:0; color:#333333; font-size: 12pt;}

div.box {
padding: 0px;
margin:0 auto;
width:340px;
position:relative;
top:50px;
border:0px solid #262626;
}

div.box h1 {
font-family: sans-serif, Arial, Helvetica;
text-shadow: 1px 1px 1px #ffffff;
margin: 0px;
color:#334455;
font-size:24pt;
padding:5px 0 5px 0px;
letter-spacing: -2px;
}


</style>

    </head>
    <body>

        <div class="box">
           <h1>Kaydınız alınmıştır. Teşekkür ederiz.</h1>
        </div>
    </body>
</html>

playground/renan/projects/staj/templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>
    <head>
        <title>Pardus StajProjeleri</title>
        <link type="text/css" rel="stylesheet" href="css/style.css">
    </head>

    <body style="background-color:#f0f0f6">
        <form action="/internshop/" method="post">
            <table cellspacing="1" width="100%" >
                <tr>
                    <td width = "40"><a style="color:#222222" href="/internshop"><img src="img/mario.png" border="0" width="30" height="30"></a></td>
                    <td><h2 style="color:#222222">Pardus InternShop</h2></td>
                    <td width="200" align="right"><h6>Kullanıcı Adı</h6></td>
                    <td width="160">
                        <input name="username" type="text">
                    </td>
                    <td width="50" align="right"><h6>Parola</h6></td>
                    <td width="180">
                        <input name="password" type="password">
                    </td>
                    <td align="right" width="40">
                        <input value="Giriş" type="submit">
                    </td>
                </tr>
            </table>
        </form>
    </body>
</html>

playground/renan/projects/staj/templates/mentor.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>
    <head>
        <script src="js/jquery-1.3.2.min.js"></script>
        <script src="js/jquery-ui-1.7.2.custom.min.js"></script>
        <script src="js/jquery.validate.js"></script>
        <link type="text/css" href="css/ui-lightness/jquery-ui-1.7.2.custom.css" rel="stylesheet" />

        <title>Proje Fikir Toplama Robotu</title>

        <style type="text/css">
body
{
font-family: Verdana, sans-serif, Arial;
font-size: 11px;
margin:0px;
padding:0px;
background-image: url("http://cakirerk.org/artwork/bg.png");
background-position: center center;
background-attachment: fixed;
}

.form{
    opacity: 0.8;
    color: #404067;
    background-color: #ffffff
}

#id_mentors {
width: 300px;
height: 300px
}

.form th
{
width: 110px;
padding:10px 20px 10px 20px;
text-align: right;
color: #333333;
font-family: Arial;
font-weight: bold;
font-size: 14px;
vertical-align: top;
}

input, textarea {
width: 300px;
border:1px solid #bbbbbb;
}

.form li{
    list-style: none;
    margin-right:10px;
}

.form ul{
    padding: 0px;
    margin: 0px;
}

.form td
{
padding:10px 20px 10px 20px;
border: 0px;
text-align: left;
font-family: Verdana, sans-serif, Arial;
font-weight: normal;
font-size: 11px;
vertical-align: middle;
}

.invalid{
    float:left;
    margin-left:10px;
    vertical-align: middle
}

.header{
    margin-top: 20px;
    font-family: Verdana, sans-serif, Arial;
    font-weight: normal;
}

.form .submit{
    text-align: center;
    border-top:2px solid #ffffff;
}

.header .logo{
    padding-right:10px
}

.title{
    height: 50px;
    letter-spacing:-2px;
    color: #333333;
    font-size: 45px;
    font-weight: bold;
    text-align: center;
    padding-bottom: 30px;
}
</style>

    </head>
    <body>
        {% include "header.html" %}

        {% if errors %}
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}

    <div class="title">{{ title }}</div>

        <form id="form" action="/mentor/" method="post">
            <table class="form" align="center" cellspacing="0" cellpadding="0">
                {{ form.as_table }}
                <tr>
                    <th></th>
                    <td></td>
                </tr>

                <tr>
                    <td class="submit" colspan="2"><input type="submit" value="Gönder"></td>
                </tr>
            </table>
        </form>

    </body>
</html>

playground/renan/projects/staj/templates/mentor_done.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>
    <head>
        <title>Proje Giriş Formu</title>
        <style type="text/css">
body
{
font-family: Verdana, sans-serif, Arial;
font-size: 11px;
margin:0px;
padding:0px;
background-image: url("http://cakirerk.org/artwork/bg.png");
background-position: center center;
background-attachment: fixed;
}

.title{
    margin-top: 50px;
    font-size: 45pt;
    color: #404067;
    text-align: center;
}

</style>

    </head>
    <body>

    <div class="title">Proje Kaydedildi.</div>

    </body>
</html>

playground/renan/projects/staj/templates/search_form.html
<html>
<head>
    <title>Search</title>
</head>
<body>
    <form action="/search/" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
</html>

playground/renan/projects/staj/templates/thanks.html
<h2>Başvurular sonlanmıştır. İlginiz için teşekkür ederiz.</h2>